# Generated by Django 4.2.6 on 2023-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
