# Generated by Django 3.2.8 on 2023-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20231209_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.URLField(max_length=500),
        ),
    ]
