# Generated by Django 3.2.8 on 2023-12-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_userprofile_celular'),
        ('usuarios', '0004_alter_places_img'),
    ]

    operations = [
    ]
