# Generated by Django 3.2.8 on 2023-12-10 05:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_merge_20231209_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastForm',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
