# Generated by Django 3.2.8 on 2023-12-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20231210_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
