# Generated by Django 3.2.8 on 2023-12-10 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_userprofile_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='opinion',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scorePlaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
