# Generated by Django 3.2.8 on 2023-12-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20231210_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='scorePlaces',
            new_name='rate',
        ),
    ]
