# Generated by Django 3.2.8 on 2023-12-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_userprofile_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
