# Generated by Django 3.2.8 on 2023-12-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_userprofile_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='opinion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
