# Generated by Django 3.2.8 on 2023-12-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20231210_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='opinion',
            new_name='rate',
        ),
    ]
